apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-ingress-contoso-com-tls-secret-csi-akv
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.key
    - objectName: ingress-internal-aks-ingress-contoso-com-tls
      key: tls.crt
  parameters:
    clientID: 4e1e31b9-25de-4c35-81ff-b66f25a81b81
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: kv-aks-nddb427jr4fd2
    objects: |
      array:
        - |
          objectName: ingress-internal-aks-ingress-contoso-com-tls
          objectType: secret
    tenantID: b9ccb062-1ade-421f-a3da-0a738577137d
